apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
   persistentVolumeClaimRetentionPolicy: # SE EXCLUIR OU REDUZIR UM STATEFULSET NÃO EXCLUIRÁ OS VOLUMES ASSOCIADOS A ELE
    whenScaled: Delete  # DELETA PVC QUANDO REPLICAS SÃO REDUZIDAS
  selector:
    matchLabels:
      app: nginx 
  serviceName: "nginx"
  replicas: 30  # ALTERAR NUMERO DE REPLICAAS
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 1 # ATUALIZA APENAS PODS COM INDICE >=1 (preserva web-0)
  minReadySeconds: 0 # by default is 0
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-pool
               - key: node-pool
                operator: In
                values: [novo-pool]
      initContainers:
        - name: volume-page
          image: busybox
          command: [ 'sh', '-c', 'echo $(hostname) > /app/index.html']
          volumeMounts:
            - mountPath: /app
              name: www
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.24
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard-rwo"
      resources:
        requests:
          storage: 8Gi #ALTERAR O TAMANHO DO VOLUME


